apiVersion: v1
kind: ServiceAccount
metadata:
  name: bot-access-robot
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: bot-access-secret
  annotations:
    kubernetes.io/service-account.name: bot-access-robot
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-access-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments","deployments/scale","deployments/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: bot-access-robot
  namespace: default
roleRef:
  kind: Role
  name: bot-access-role
  apiGroup: rbac.authorization.k8s.io
