HELP = ["HELP", "AIDE-MOI", "3AWENI"]
LIST = ["LIST", "LISTE", "LISTA"]
POD = ["POD", "MACHINE", "MAKINA", "PODS", "MACHINES", "MAKINET"]
LOG = ["LOG", "LOGS"]
DEPLOYMENT = ["DEPLOYMENT", "DEPLOYMENTS", "APPLICATION", "APPLICATIONS"]
SERVICE = ["SERVICE", "SERVICES"]

